class MockData {
  static final List<Map<String, dynamic>> drivers = [
    {
      'id': '1',
      'name': 'John Smith',
      'photo': 'https://i.pravatar.cc/150?img=1',
      'rating': 4.8,
      'reviews': 127,
      'verified': true,
      'licenseType': 'Class A CDL',
      'experience': '8 years',
      'availability': true,
      'location': 'Chicago, IL',
      'hourlyRate': '\$28/hr',
    },
    {
      'id': '2',
      'name': 'Sarah Johnson',
      'photo': 'https://i.pravatar.cc/150?img=5',
      'rating': 4.9,
      'reviews': 89,
      'verified': true,
      'licenseType': 'Class B CDL',
      'experience': '5 years',
      'availability': true,
      'location': 'Chicago, IL',
      'hourlyRate': '\$25/hr',
    },
    {
      'id': '3',
      'name': 'Mike Davis',
      'photo': 'https://i.pravatar.cc/150?img=3',
      'rating': 4.6,
      'reviews': 64,
      'verified': false,
      'licenseType': 'Class A CDL',
      'experience': '3 years',
      'availability': false,
      'location': 'Chicago, IL',
      'hourlyRate': '\$24/hr',
    },
  ];

  static final List<Map<String, dynamic>> jobs = [
    {
      'id': '1',
      'title': 'Long Distance Truck Driver',
      'company': 'Swift Logistics',
      'logo': 'https://i.pravatar.cc/100?img=10',
      'location': 'Chicago, IL',
      'salary': '\$3,500 - \$4,500/month',
      'type': 'Full-time',
      'posted': '2 hours ago',
      'description': 'Looking for experienced CDL driver for long-haul deliveries across the country.',
      'requirements': ['CDL-A License', '3+ years experience', 'Clean record'],
      'isUrgent': true,
    },
    {
      'id': '2',
      'title': 'Delivery Driver',
      'company': 'FastShip Inc.',
      'logo': 'https://i.pravatar.cc/100?img=11',
      'location': 'Los Angeles, CA',
      'salary': '\$2,800 - \$3,200/month',
      'type': 'Part-time',
      'posted': '5 hours ago',
      'description': 'Part-time delivery driver for residential areas.',
      'requirements': ['Valid Driver License', 'Own vehicle', 'Smartphone'],
      'isUrgent': false,
    },
    {
      'id': '3',
      'title': 'OTR Truck Driver',
      'company': 'Mega Transport',
      'logo': 'https://i.pravatar.cc/100?img=12',
      'location': 'Dallas, TX',
      'salary': '\$4,000 - \$5,000/month',
      'type': 'Full-time',
      'posted': '1 day ago',
      'description': 'Over-the-road driver for long-haul routes across USA.',
      'requirements': ['CDL-A', '5+ years experience', 'HAZMAT endorsement'],
      'isUrgent': false,
    },
    {
      'id': '4',
      'title': 'Local Delivery Driver',
      'company': 'CityExpress',
      'logo': 'https://i.pravatar.cc/100?img=13',
      'location': 'Miami, FL',
      'salary': '\$2,500 - \$3,000/month',
      'type': 'Contract',
      'posted': '3 hours ago',
      'description': 'Local deliveries in Miami metro area.',
      'requirements': ['Class B License', '1+ year experience'],
      'isUrgent': true,
    },
    {
      'id': '5',
      'title': 'Bus Driver',
      'company': 'TransCity',
      'logo': 'https://i.pravatar.cc/100?img=14',
      'location': 'New York, NY',
      'salary': '\$3,200 - \$3,800/month',
      'type': 'Full-time',
      'posted': '1 day ago',
      'description': 'Public transit bus driver position.',
      'requirements': ['CDL-B', 'Passenger transport license', 'Clean record'],
      'isUrgent': false,
    },
    {
      'id': '6',
      'title': 'Warehouse Driver',
      'company': 'QuickStock',
      'logo': 'https://i.pravatar.cc/100?img=15',
      'location': 'Phoenix, AZ',
      'salary': '\$22 - \$26/hour',
      'type': 'Part-time',
      'posted': '6 hours ago',
      'description': 'Driver for warehouse pickups and deliveries.',
      'requirements': ['Valid License', 'Forklift certification'],
      'isUrgent': false,
    },
    {
      'id': '7',
      'title': 'Tanker Truck Driver',
      'company': 'Fluid Haulers',
      'logo': 'https://i.pravatar.cc/100?img=16',
      'location': 'Houston, TX',
      'salary': '\$4,500 - \$5,500/month',
      'type': 'Full-time',
      'posted': '12 hours ago',
      'description': 'Transport liquid cargo in tanker trucks.',
      'requirements': ['CDL-A', 'Tanker endorsement', '2+ years experience'],
      'isUrgent': true,
    },
    {
      'id': '8',
      'title': 'Rideshare Driver',
      'company': 'GoRide',
      'logo': 'https://i.pravatar.cc/100?img=17',
      'location': 'San Francisco, CA',
      'salary': '\$25 - \$35/hour',
      'type': 'Part-time',
      'posted': '2 days ago',
      'description': 'Flexible driving opportunity with GoRide.',
      'requirements': ['4+ door vehicle', 'Valid License', 'Smartphone'],
      'isUrgent': false,
    },
  ];

  static final List<Map<String, dynamic>> applications = [
    {
      'id': '1',
      'jobTitle': 'CDL Driver Needed',
      'company': 'Swift Logistics',
      'logo': 'https://i.pravatar.cc/100?img=10',
      'appliedDate': 'March 15, 2026',
      'status': 'Under Review',
      'statusColor': 0xFFF59E0B,
    },
    {
      'id': '2',
      'jobTitle': 'Delivery Driver',
      'company': 'FastShip Inc.',
      'logo': 'https://i.pravatar.cc/100?img=11',
      'appliedDate': 'March 12, 2026',
      'status': 'Interview Scheduled',
      'statusColor': 0xFF10B981,
    },
  ];

  static final List<Map<String, dynamic>> messages = [
    {
      'id': '1',
      'name': 'Swift Logistics',
      'photo': 'https://i.pravatar.cc/100?img=10',
      'lastMessage': 'Your application is under review...',
      'time': '10:30 AM',
      'unread': 2,
    },
    {
      'id': '2',
      'name': 'FastShip Inc.',
      'photo': 'https://i.pravatar.cc/100?img=11',
      'lastMessage': 'Great! See you tomorrow at 9 AM.',
      'time': 'Yesterday',
      'unread': 0,
    },
  ];

  static final Map<String, dynamic> currentDriver = {
    'name': 'John Smith',
    'photo': 'https://i.pravatar.cc/150?img=1',
    'rating': 4.8,
    'reviews': 127,
    'licenseType': 'Class A CDL',
    'experience': '8 years',
    'availability': true,
    'location': 'Chicago, IL',
    'phone': '+1 (555) 123-4567',
    'email': 'john.smith@email.com',
    'verified': true,
    'joinedDate': 'January 2024',
    'completedJobs': 156,
    'responseRate': '98%',
    'acceptRate': '92%',
  };

  static final List<String> countries = [
    'United States',
    'United Kingdom',
    'Germany',
    'France',
    'Spain',
    'Italy',
    'Netherlands',
    'Belgium',
    'Canada',
    'Australia',
    'Japan',
    'UAE',
    'Saudi Arabia',
    'Qatar',
    'Kuwait',
    'Bahrain',
    'Oman',
    'Egypt',
    'Morocco',
    'Tunisia',
    'Algeria',
    'Nigeria',
    'Kenya',
    'South Africa',
    'Brazil',
    'Mexico',
  ];

  static final Map<String, List<String>> citiesByCountry = {
    'United States': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'United Kingdom': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Bristol', 'Sheffield', 'Leeds', 'Edinburgh', 'Leicester'],
    'Germany': ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Stuttgart', 'Dusseldorf', 'Dortmund', 'Essen', 'Leipzig'],
    'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
    'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Malaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'],
    'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania'],
    'Canada': ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener'],
    'UAE': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain', 'Khalifa City', 'Jebel Ali'],
    'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Abha', 'Tabuk', 'Buraidah', 'Qatif'],
  };

  static final List<Map<String, String>> languages = [
    {'code': 'en', 'name': 'English', 'native': 'English'},
    {'code': 'fr', 'name': 'French', 'native': 'Francais'},
    {'code': 'es', 'name': 'Spanish', 'native': 'Espanol'},
    {'code': 'de', 'name': 'German', 'native': 'Deutsch'},
    {'code': 'it', 'name': 'Italian', 'native': 'Italiano'},
    {'code': 'pt', 'name': 'Portuguese', 'native': 'Portugues'},
    {'code': 'ar', 'name': 'Arabic', 'native': 'العربية'},
    {'code': 'zh', 'name': 'Chinese', 'native': '中文'},
    {'code': 'ja', 'name': 'Japanese', 'native': '日本語'},
    {'code': 'ko', 'name': 'Korean', 'native': '한국어'},
    {'code': 'hi', 'name': 'Hindi', 'native': 'हिन्दी'},
    {'code': 'ru', 'name': 'Russian', 'native': 'Русский'},
    {'code': 'tr', 'name': 'Turkish', 'native': 'Turkce'},
    {'code': 'nl', 'name': 'Dutch', 'native': 'Nederlands'},
    {'code': 'pl', 'name': 'Polish', 'native': 'Polski'},
  ];

  static final List<String> licenseTypes = [
    'Class A CDL',
    'Class B CDL',
    'Class C CDL',
    'CDL-A',
    'CDL-B',
    'CDL-C',
    'Standard Driving License',
    'Provisional License',
    'Learner\'s Permit',
  ];
}